---
Description: Creating Simple EC2 via CICD
Parameters:
  TagValue:
    Type: String
    Description: Ec2 Tag
  ImageId:
    Type: String
    Description: Image ID
  InstanceType:
    Type: String
    Description: InstanceType
  AvailabilityZone:
    Type: String
    Description: AvailabilityZone
    
Resources:
  ansiblecontroller:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      Tags:
        - Key: Name
          Value: !Ref TagValue
