
pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    tty: true
    command:
    - /bin/bash
'''
       defaultContainer 'aws-cli'
        }
    }
    stages {
        stage('Clone') {
            steps {
                sh 'pwd'
                sh 'ls'
            }
        }
      
       stage('Main') {
            steps {
                container('aws-cli') {
                    withCredentials([usernamePassword(credentialsId: 'aws-keys', passwordVariable: 'AWS_SECRET_ACCESS_KEY', usernameVariable: 'AWS_ACCESS_KEY_ID')]) {
                        sh '''
                        cd $WORKSPACE/cloud-formation/ec2/'
                        ls -lrt
                        aws configure set region us-east-1
                        aws cloudformation create-stack --template-body file://0-just-ec2.yaml --parameters file://0-just-ec2.json --stack-name just-ec2
                        '''
                    }
                }
            }
        }
    }
}
